### ISSUE TITLE
cmake ... doesn't work

### ISSUE THREAD

**Issue by mrcarlfox** [AIWintermuteAI/Seeed_reTerminal_LVGL_UI_Demo#1]
Here is what I get.
pi@raspberrypi:~/pc_simulator/build $ cmake ..
-- Configuring done
CMake Error at CMakeLists.txt:19 (add_executable):
  Target "main" links to target "lvgl::examples" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at CMakeLists.txt:19 (add_executable):
  Target "main" links to target "lvgl::demos" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

CMake Error at CMakeLists.txt:19 (add_executable):
  Target "main" links to target "lvgl::drivers" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by AIWintermuteAI** [comment]
What is the pc_simulator folder?

**Comment by mrcarlfox** [comment]
It is the folder I get from downloading this link https://github.com/littlevgl/pc_simulator.git
I get the error when I run these commands
cd pc_simulator
mkdir build
cd build.
cmake ..
make -j4

**Comment by AIWintermuteAI** [comment]
I see. In that case, please make an issue about your problem in https://github.com/littlevgl/pc_simulator.git repository. Thanks!
